class ConstantsWrapper:

    ELEMENT_AVOID_KEY = 'A'
    ELEMENT_PRIORITIZE_KEY = 'P'
    ELEMENT_MINIMIZE_KEY = 'M'
    ELEMENT_REMOVE_KEY = 'R'
    ELEMENT_ACTION_KEYS = (
        ELEMENT_AVOID_KEY,
        ELEMENT_PRIORITIZE_KEY,
        ELEMENT_MINIMIZE_KEY,
        ELEMENT_REMOVE_KEY,
    )

    # Deductions
    DEDUCT_AVOID = 60
    DEDUCT_GR_MIN2 = 60
    DEDUCT_GR_MIN1 = 30
    DEDUCT_LT_MIN1 = 15
    DEDUCT_LT_MIN1_VEESTRO = 20

    DEDUCT_SINGLE_VALUE = 30

    # Additions
    ADD_PRIOR = 10
    LIKED_MEAL = 10

    ADD_CALORIES = 10
    DEDUCT_CALORIES = 10

    DEFAULT_INGREDIENT_MULTIPLIER = 1
    INGREDIENT_PROGRESS_MULTIPLIER = 1.5

    # REPEAT
    REPEAT_ZERO = -50
    REPEAT_ONE = -30
    REPEAT_TWO = -15
    REPEAT_CUM = - 5

    SUBSCRIPTION_WEEKLY_INTERVAL = 1

    DEFAULT_RECOMMENDATION_SCORE = 100


constants_wrapper = ConstantsWrapper()